replicaCount: 2

image:
  repository: ghcr.io/bertds-student/fastapi-intro
  tag: v1.0.0

nameOverride: "nathan-fastapi"
fullNameOverride: "nathan-fastapi-demo"

serviceAccount:
    create: true
    name: helm-service-account ## This is a name you can choose yourself

## Keep these empty for the first try.
imagePullSecrets: [name : "ghrc-desutter-bert"] # Here you can fill in your own Pull Secret if you do want to work with your own repository
nodeSelector: {kubernetes.io/hostname: "desutter-bert"} # Fill in the right Node Selector here.